# Generated by Django 5.2.12 on 2026-03-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_user', models.DecimalField(decimal_places=2, help_text='Price per staff slot', max_digits=12)),
                ('features', models.JSONField(default=list, help_text='List of feature names')),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('renewal_period_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('max_staff', models.PositiveIntegerField(default=2)),
                ('reduced_slots_balance', models.PositiveIntegerField(default=0)),
                ('next_billing_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_subscriptions', to='billing.plan')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('NewSubscription', 'NewSubscription'), ('Renewal', 'Renewal'), ('StaffAddition', 'StaffAddition')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('staff_count_change', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='stores.store')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.subscription')),
            ],
        ),
    ]
