# Generated by Django 5.2.12 on 2026-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_auto_renew_paymentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='save_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('NewSubscription', 'NewSubscription'), ('Renewal', 'Renewal'), ('StaffAddition', 'StaffAddition'), ('CardTokenization', 'CardTokenization')], max_length=20),
        ),
    ]
