# Generated by Django 5.2.12 on 2026-03-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
        ('stores', '0002_subscription_amount_per_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='stores.store'),
        ),
    ]
