# Generated by Django 5.2.12 on 2026-03-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0002_customer_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='sales.customer'),
        ),
    ]
