# Generated by Django 5.2.12 on 2026-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
