# Generated by Django 5.2.12 on 2026-03-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_condition_product_conditions'),
        ('stores', '0002_subscription_amount_per_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='stores.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('name', 'store')},
        ),
    ]
