# Generated by Django 5.2.12 on 2026-04-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_sold_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tac', models.CharField(db_index=True, max_length=8, unique=True)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('aka', models.JSONField(blank=True, default=list)),
                ('contributor', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField(blank=True, default='')),
                ('gsmarena_1', models.URLField(blank=True, default='')),
                ('gsmarena_2', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tac'],
            },
        ),
    ]
