# Generated by Django 5.2.12 on 2026-03-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_subscription_amount_per_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_user', models.DecimalField(decimal_places=2, help_text='Price per staff slot', max_digits=12)),
                ('features', models.JSONField(default=list, help_text='List of feature names')),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('renewal_period_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='amount_per_staff',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_type_legacy',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='stores.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_subscriptions', to='stores.plan'),
        ),
    ]
