# Generated by Django 5.2.12 on 2026-03-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_plan_remove_subscription_amount_per_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store'),
        ),
    ]
