# Generated by Django 5.2.12 on 2026-03-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_subscription_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='cover_image',
            new_name='cover_picture',
        ),
    ]
